### ISSUE TITLE
parameter to reproduce paper's result

### ISSUE THREAD

**Issue by hongyuntw** [zhichaoxu-shufe/understanding-reviews#1]
Dear author
Thank you for your great work and make it open source !
I want to reproduce the experiment on paper
Could I know what parameters should I set in train.py ?
I am running the Beauty dataset
```
	# hyperparameters
	parser.add_argument("--kernel_size", type=int, default=3)
	parser.add_argument("--hidden_dim", type=int, default=10)
	parser.add_argument("--embedding_dim", type=int, default=300)
	parser.add_argument("--latent_dim", type=int, default=10)
	parser.add_argument("--dropout", type=float, default=0.5)
	parser.add_argument("--arch", type=str, default="CNN")

	parser.add_argument("--epochs", type=int, default=1)
	parser.add_argument("--batch_size", type=int, default=32)
	parser.add_argument("--lr", type=float, default=1e-3)
	parser.add_argument("--lr_decay", type=float, default=0.0)
	parser.add_argument("--decay_patience", type=int, default=0)
	parser.add_argument("--max_grad_norm", type=float, default=5.0)
	parser.add_argument("--patience", type=int, default=5)
```

thank you again for your great work, it's interesting.

**Comment by zhichaoxu-shufe** [comment]
hello, you should be able to reproduce the result using the default hyperparameters after ~30 epochs

**Comment by hongyuntw** [comment]
@zhichaoxu-shufe  thank you for replying to me

But when I run the train.sh
follow these augment
```
dataset="Digital_Music" 
python train.py \
--input_dir "./datasets/${dataset}/" \
--dataset "./datasets/${dataset}/" \
--log True --log_dir "./logs/${dataset}"
```
will occur this Error, and message is

> Traceback (most recent call last):
>   File "train.py", line 76, in <module>
>     experiment.train()
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/engine.py", line 244, in train
>     self.train_one_epoch(epoch)
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/engine.py", line 114, in train_one_epoch
>     for i, (u_ids_batch, i_ids_batch, u_docs_batch, i_docs_batch, u_docs_batch_word_masks, i_docs_batch_word_masks) in enumerate(self.train_dataloader):
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
>     return self._process_data(data)
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
>     raise self.exc_type(msg)
> ValueError: Caught ValueError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/data.py", line 106, in collate_fn
>     i_docs_batch= LongTensor(i_docs_batch)
> ValueError: expected sequence of length 500 at dim 2 (got 2500)


I have checked the shape of i_docs_batch by using
```
        u_ids_batch = LongTensor(u_ids_batch)
        i_ids_batch = LongTensor(i_ids_batch)
        print(torch.tensor(u_docs_batch).shape)
        print(torch.tensor(i_docs_batch).shape)

        u_docs_batch = LongTensor(u_docs_batch)
        i_docs_batch= LongTensor(i_docs_batch)
```

and the error will be 

> torch.Size([16, 5, 500])
> torch.Size([16, 5, 500])
>   0%|                                                                                                                                                                   | 1/7917 [00:00<27:56,  4.72it/s]torch.Size([16, 5, 500])
> torch.Size([16, 5, 500])
> Traceback (most recent call last):
>   File "train.py", line 76, in <module>
>     experiment.train()
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/engine.py", line 244, in train
>     self.train_one_epoch(epoch)
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/engine.py", line 114, in train_one_epoch
>     for i, (u_ids_batch, i_ids_batch, u_docs_batch, i_docs_batch, u_docs_batch_word_masks, i_docs_batch_word_masks) in enumerate(self.train_dataloader):
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
>     return self._process_data(data)
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
>     raise self.exc_type(msg)
> TypeError: Caught TypeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/nlplab/harry/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/nlplab/harry/review_rec/understanding-reviews/deepconn/data.py", line 107, in collate_fn
>     print(torch.tensor(i_docs_batch).shape)
> TypeError: new(): invalid data type 'str'

I have no idea to solve this error, and this error will occur on other datasets too.

**Comment by zhichaoxu-shufe** [comment]
The same code works at my end, and it seems the error is because of the dataloader is not loading because of the get_item function, you should check there, it is possible the meta.pkl is wrongly built

**Comment by hongyuntw** [comment]
Thanks a lot
I have an other question, in the data.py
when we sample the negative data, it's look like just simple random sample strategy
```
            n_ids = np.random.randint(1, self.item_num, size=self.negN)
            i_ids = [i_id]
            i_docs = [i_doc]
            u_ids = [u_id]
            u_docs = [u_doc]

            for n_id in n_ids:
                i_ids.append(n_id)
                i_docs.append(self.meta['item_docs'][n_id])
                # print(i_docs)
                u_ids.append(u_id)
                u_docs.append(u_doc)
```
But in the paper, there has a "two-stage retrieval & reranking strategy" to sample negative data, and I cant find the code in this repo. 
And I also want to know how to determine the negative data number during training and validate (in your code that is 4 and 99).
Thank you a lot !

**Comment by zhichaoxu-shufe** [comment]
hello,

after your training of matrix factorization, you should be able to get a ranklist. _DeepCoNN Dataset Class_ will take in this ranklist and use it in test stage. However, it can take a long time for DeepCoNN to output a  ranklist on the 1k items per user, so we use a smaller validation set consisting of 99 neg items. Basically, when the valid result stops improving, we know it's time to test, then we use the actual testset generate by _DeepCoNN Dataset Class_. 

for the choice of negative data number for training, it is a hyperparameter of your choice, we use 4 because it is a good balance between training time and performance.

**Comment by zhichaoxu-shufe** [comment]
you should be able to understand how the whole procedure works by reading the train, valid, test functions in deepconn/engine.py
